[package]
name = "soyal_client"
version = "0.1.0"
edition = "2018"
authors = ["Juhasz Sandor <blackghost1987@gmail.com>"]

[dependencies]
enum_primitive = "0.1"
macaddr = { version = "1.0", features = ["serde_std"] }
serde = { version = "1.0", features = ["derive"] }
