[package]
name = "soyal_client"
version = "0.1.0"
edition = "2018"
authors = ["Juhasz Sandor <blackghost1987@gmail.com>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = { version = "2.0", features = ["serde"] }
